config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :routes

  resources :pickup_point_time_details do 
      collection do
        get 'get_route_start_time'
        get 'get_location'
      end
  end

  root to: "routes#index"

  resources :pickup_route_start_times

  resources :locations

  resources :drop_route_start_times

  resources :drop_point_time_details do 
    collection do
        get 'get_route_start_time'
        get 'get_location'
    end
  end
  

end

app/models/pickup_point_time_detail.rb
class PickupPointTimeDetail < ActiveRecord::Base
	belongs_to :route
	belongs_to :location
	belongs_to :pickup_route_start_time

	def pickup_time
		read_attribute(:pickup_time).to_s(:desire)  unless read_attribute(:pickup_time).nil?
	end

end

app/controllers/pickup_point_time_details_controller.rb
class PickupPointTimeDetailsController < ApplicationController
  before_action :set_pickup_point_time_detail, only: [:show, :edit, :update, :destroy]

  # GET /pickup_point_time_details
  # GET /pickup_point_time_details.json
  def index
    @pickup_point_time_details = PickupPointTimeDetail.includes(:route, :location, :pickup_route_start_time)
  end

  # GET /pickup_point_time_details/1
  # GET /pickup_point_time_details/1.json
  def show
  end

  # GET /pickup_point_time_details/new
  def new
    @pickup_point_time_detail = PickupPointTimeDetail.new
  end

  # GET /pickup_point_time_details/1/edit
  def edit
  end

  # POST /pickup_point_time_details
  # POST /pickup_point_time_details.json
  def create
    @pickup_point_time_detail = PickupPointTimeDetail.new(pickup_point_time_detail_params)

    respond_to do |format|
      if @pickup_point_time_detail.save
        format.html { redirect_to pickup_point_time_details_path, notice: 'Pickup point time detail was successfully created.' }
        format.json { render :show, status: :created, location: @pickup_point_time_detail }
      else
        format.html { render :new }
        format.json { render json: @pickup_point_time_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pickup_point_time_details/1
  # PATCH/PUT /pickup_point_time_details/1.json
  def update
    respond_to do |format|
      if @pickup_point_time_detail.update(pickup_point_time_detail_params)
        format.html { redirect_to pickup_point_time_details_path, notice: 'Pickup point time detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @pickup_point_time_detail }
      else
        format.html { render :edit }
        format.json { render json: @pickup_point_time_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pickup_point_time_details/1
  # DELETE /pickup_point_time_details/1.json
  def destroy
    @pickup_point_time_detail.destroy
    respond_to do |format|
      format.html { redirect_to pickup_point_time_details_url, notice: 'Pickup point time detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_route_start_time
     # @route = Route.find(params[:route_id])
     #@pickup_route_start_times = Route.joins(:pickup_route_start_times).where(params[:route_id])
      @pickup_route_start_times = Route.find(params[:route_id]).pickup_route_start_times
      # @route = Route.find(params[:route_id])
    respond_to do |format|
      format.js
    end
  end

  def get_location
     # @route = Route.find(params[:route_id])
     # @location = route.locations
    # @route = Route.joins(:pickup_route_start_times).where(params[:route_id])
    # @locations = Route.joins(:locations).where(params[:route_id])
    # @locations = Route.find(params[:route_id]).locations
    @locations = Route.find(params[:route_id]).locations
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pickup_point_time_detail
      @pickup_point_time_detail = PickupPointTimeDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pickup_point_time_detail_params
      #params[:pickup_point_time_detail]
      params.require(:pickup_point_time_detail).permit(:route_id, :location_id, :pickup_route_start_time_id, :pickup_time)
    end
end

app/helpers/pickup_point_time_details_helper.rb
module PickupPointTimeDetailsHelper
end

app/views/pickup_point_time_details/_form.html.erb
<%= form_for(@pickup_point_time_detail) do |f| %>
  <% if @pickup_point_time_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pickup_point_time_detail.errors.count, "error") %> prohibited this pickup_point_time_detail from being saved:</h2>

      <ul>
      <% @pickup_point_time_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :route_name %><br />
    <%= f.collection_select :route_id, Route.all, :id, :name, prompt: true %>
  </div>

<br/>
<%= @pickup_route_start_times %>
  <div class="field">
  <%= f.label :route_start_time %>
  <% pickup_route_start_times = @pickup_route_start_times.present? ? @pickup_route_start_times : @pickup_point_time_detail.try(:route).try(:pickup_route_start_times) %>
  <div id="route_start_time_container">
    <%= render "route_start_time", pickup_route_start_times: pickup_route_start_times if pickup_route_start_times.present?  %>
  </div>
  </div>
<br/>

  <div class="field">
  <%= f.label :pickup_point %>
  <div id="location_container">
  <% locations = @locations.present? ? @locations : @pickup_point_time_detail.try(:route).try(:locations) %>
    <%= render "location", locations: locations if locations.present?  %>
  </div>
  </div>

  <div class="pickup_time_field" >
    <%= f.label :pickup_time %><br />
    <%= f.text_field :pickup_time %>
  </div>

  <br/>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pickup_point_time_details/_location.erb
 <%# locations = route.locations %>
<%= collection_select "pickup_point_time_detail",:location_id, locations, :id, :name, prompt: true %>

app/views/pickup_point_time_details/_route_start_time.erb
 <%# pickup_route_start_times = route.pickup_route_start_times %>
 
 <%#= raise pickup_route_start_times.inspect %>

<%= collection_select "pickup_point_time_detail",:pickup_route_start_time_id, pickup_route_start_times, :id, :pickup_start_time, prompt: true %>

app/views/pickup_point_time_details/edit.html.erb
<h1>Editing pickup_point_time_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @pickup_point_time_detail %> |
<%= link_to 'Back', pickup_point_time_details_path %>

app/views/pickup_point_time_details/get_route_start_time.js.erb
$('#route_start_time_container').html('<%=escape_javascript render("route_start_time", pickup_route_start_times: @pickup_route_start_times) %>');

app/views/pickup_point_time_details/index.html.erb
<h1>Listing pickup_point_time_details</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pickup_point_time_details.each do |pickup_point_time_detail| %>
      <tr>
        <td><%= pickup_point_time_detail.try(:route).try(:name) %>&nbsp;&nbsp;|&nbsp;&nbsp;</td>
        <td><%= pickup_point_time_detail.try(:pickup_route_start_time).try(:pickup_start_time) %>&nbsp;&nbsp;|&nbsp;&nbsp;</td>
        <td><%= pickup_point_time_detail.try(:location).try(:name) %>&nbsp;&nbsp;|&nbsp;&nbsp;</td>
        <td><%= pickup_point_time_detail.try(:pickup_time) %>&nbsp;&nbsp;|&nbsp;&nbsp;</td>
        <td><%= link_to 'Show', pickup_point_time_detail %></td>
        <td><%= link_to 'Edit', edit_pickup_point_time_detail_path(pickup_point_time_detail) %></td>
        <td><%= link_to 'Destroy', pickup_point_time_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pickup point time detail', new_pickup_point_time_detail_path %>

app/views/pickup_point_time_details/new.html.erb
<h1>New pickup_point_time_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', pickup_point_time_details_path %>

app/views/pickup_point_time_details/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pickup_point_time_detail_path(@pickup_point_time_detail) %> |
<%= link_to 'Back', pickup_point_time_details_path %>