config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :routes

  resources :pickup_point_time_details do 
      collection do
        get 'get_route_start_time'
        get 'get_location'
      end
  end

  root to: "routes#index"

  resources :pickup_route_start_times

  resources :locations

  resources :drop_route_start_times

  resources :drop_point_time_details do 
    collection do
        get 'get_route_start_time'
        get 'get_location'
    end
  end
  

end

app/models/drop_point_time_detail.rb
class DropPointTimeDetail < ActiveRecord::Base
	belongs_to :route
	belongs_to :location
	belongs_to :drop_route_start_time

	def drop_time
		read_attribute(:drop_time).to_s(:desire)  unless read_attribute(:drop_time).nil?
	end

end

app/controllers/drop_point_time_details_controller.rb
class DropPointTimeDetailsController < ApplicationController
  before_action :set_drop_point_time_detail, only: [:show, :edit, :update, :destroy]

  # GET /drop_point_time_details
  # GET /drop_point_time_details.json
  def index
    # @drop_point_time_details = DropPointTimeDetail.all
    @drop_point_time_details = DropPointTimeDetail.includes(:route, :location, :drop_route_start_time)
  end

  # GET /drop_point_time_details/1
  # GET /drop_point_time_details/1.json
  def show
  end

  # GET /drop_point_time_details/new
  def new
    @drop_point_time_detail = DropPointTimeDetail.new
  end

  # GET /drop_point_time_details/1/edit
  def edit
  end

  # POST /drop_point_time_details
  # POST /drop_point_time_details.json
  def create
    @drop_point_time_detail = DropPointTimeDetail.new(drop_point_time_detail_params)

    respond_to do |format|
      if @drop_point_time_detail.save
        format.html { redirect_to drop_point_time_details_path, notice: 'Drop point time detail was successfully created.' }
        format.json { render :show, status: :created, location: @drop_point_time_detail }
      else
        format.html { render :new }
        format.json { render json: @drop_point_time_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drop_point_time_details/1
  # PATCH/PUT /drop_point_time_details/1.json
  def update
    respond_to do |format|
      if @drop_point_time_detail.update(drop_point_time_detail_params)
        format.html { redirect_to drop_point_time_details_path, notice: 'Drop point time detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @drop_point_time_detail }
      else
        format.html { render :edit }
        format.json { render json: @drop_point_time_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drop_point_time_details/1
  # DELETE /drop_point_time_details/1.json
  def destroy
    @drop_point_time_detail.destroy
    respond_to do |format|
      format.html { redirect_to drop_point_time_details_url, notice: 'Drop point time detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_route_start_time
      @drop_route_start_times = Route.find(params[:route_id]).drop_route_start_times
      
     respond_to do |format|
      format.js
    end
  end

  def get_location
    @locations = Route.find(params[:route_id]).locations
    respond_to do |format|
      format.js
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drop_point_time_detail
      @drop_point_time_detail = DropPointTimeDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drop_point_time_detail_params
      # params[:drop_point_time_detail]
      params.require(:drop_point_time_detail).permit(:route_id, :location_id, :drop_route_start_time_id, :drop_time)
    end
end

app/helpers/drop_point_time_details_helper.rb
module DropPointTimeDetailsHelper
end

app/views/drop_point_time_details/_form.html.erb
<%= form_for(@drop_point_time_detail) do |f| %>
<% if @drop_point_time_detail.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@drop_point_time_detail.errors.count, "error") %> prohibited this drop_point_time_detail from being saved:</h2>

  <ul>
    <% @drop_point_time_detail.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :route_name %><br />
  <%= f.collection_select :route_id, Route.all, :id, :name, prompt: true %>
</div>

<br/>
 <%#= @drop_point_time_detail %>
<div class="field">
   <%= f.label :route_start_time %>
  <% drop_route_start_times =  @drop_route_start_times.present? ?  @drop_route_start_times : @drop_point_time_detail.try(:route).try(:drop_route_start_times) %>
  <div id="route_start_time_container">
    <%= render "route_start_time", drop_route_start_times: drop_route_start_times if drop_route_start_times.present?  %>
  </div>
</div>
<br/>

<div class="field">
  <%= f.label :drop_point %>
  <div id="location_container">
    <% locations = @locations.present? ? @locations : @drop_point_time_detail.try(:route).try(:locations) %>
      <%= render "location", locations: locations if locations.present?  %>
  </div>
</div>

<div class="drop_time_field" >
  <%= f.label :drop_time %><br />
  <%= f.text_field :drop_time %>
</div>

<br/>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/drop_point_time_details/_location.erb
 <%# locations = route.locations %>
<%= collection_select "drop_point_time_detail",:location_id, locations, :id, :name, prompt: true %>

app/views/drop_point_time_details/edit.html.erb
<h1>Editing drop_point_time_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @drop_point_time_detail %> |
<%= link_to 'Back', drop_point_time_details_path %>

app/views/drop_point_time_details/get_location.js.erb
$('#location_container').html('<%=escape_javascript render("location", locations: @locations) %>');

app/views/drop_point_time_details/get_route_start_time.js.erb
$('#route_start_time_container').html('<%=escape_javascript render("route_start_time", drop_route_start_times: @drop_route_start_times) %>');

app/views/drop_point_time_details/index.html.erb
<h1>Listing drop_point_time_details</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drop_point_time_details.each do |drop_point_time_detail| %>
      <tr>
      <td><%= drop_point_time_detail.try(:route).try(:name) %>&nbsp;&nbsp;|&nbsp;&nbsp;</td>
        <td><%= drop_point_time_detail.try(:drop_route_start_time).try(:drop_start_time) %>&nbsp;&nbsp;|&nbsp;&nbsp;</td>
        <td><%= drop_point_time_detail.try(:location).try(:name) %>&nbsp;&nbsp;|&nbsp;&nbsp;</td>
        <td><%= drop_point_time_detail.try(:drop_time) %>&nbsp;&nbsp;|&nbsp;&nbsp;</td>
        <td><%= link_to 'Show', drop_point_time_detail %></td>
        <td><%= link_to 'Edit', edit_drop_point_time_detail_path(drop_point_time_detail) %></td>
        <td><%= link_to 'Destroy', drop_point_time_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drop point time detail', new_drop_point_time_detail_path %>

app/views/drop_point_time_details/new.html.erb
<h1>New drop_point_time_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', drop_point_time_details_path %>

app/views/drop_point_time_details/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_drop_point_time_detail_path(@drop_point_time_detail) %> |
<%= link_to 'Back', drop_point_time_details_path %>