config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :routes

  resources :pickup_point_time_details do 
      collection do
        get 'get_route_start_time'
        get 'get_location'
      end
  end

  root to: "routes#index"

  resources :pickup_route_start_times

  resources :locations

  resources :drop_route_start_times

  resources :drop_point_time_details do 
    collection do
        get 'get_route_start_time'
        get 'get_location'
    end
  end
  

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :route

	has_many :pickup_point_time_details, dependent: :destroy
	has_many :drop_point_time_details, dependent: :destroy


	ROUTE_TYPES = ["Short", "Medium", "Long"]

	INDUSTRIAL_STOP = ["YES" , "NO" ]

	validates :name, presence: true
	validates :route_id, presence: true

	def industrial_stop
		# debugger
		read_attribute(:industrial_stop).present? ? "YES" : "NO" unless read_attribute(:industrial_stop).nil?
	end

	def industrial_stop=(value)
		 value.eql?("YES") ? write_attribute(:industrial_stop, true) : write_attribute(:industrial_stop, false)
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.includes(:route)
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      # params[:location]
      params.require(:location).permit(:route_id, :name, :latitude, :longitude, :route_type, :industrial_stop)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :route_name %><br />
    <%= f.collection_select :route_id, Route.all, :id, :name, prompt: true %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
</div><br/>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
</div><br/>

  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
</div><br/>

  <div class="field">
    <%= f.label :route_type %><br />
    <%= f.select :route_type , Location::ROUTE_TYPES, prompt: true %>
</div><br/>

<div class="field">
    <%= f.label :industrial_stop %><br />
    <%= f.select :industrial_stop , Location::INDUSTRIAL_STOP, prompt: true %>
</div><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.route.name %>|</td>
        <td><%= location.name %>|</td>
        <td><%= location.latitude %>|</td>
        <td><%= location.longitude %>|</td>
        <td><%= location.route_type %>|</td>
        <td><%= location.industrial_stop %>|</td>
        <td><%= link_to 'Show', location %>|</td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>